# This file was automatically generated by bakefile.
#
# Any manual changes will be lost if it is regenerated,
# modify the source .bkl file instead if possible.

# You may define standard make variables such as CFLAGS or
# CXXFLAGS to affect the build. For example, you could use:
#
#      make CXXFLAGS=-g
#
# to build with debug information. The full list of variables
# that can be used by this makefile is:
# AR, CC, CFLAGS, CPPFLAGS, CXX, CXXFLAGS, LD, LDFLAGS, MAKE, RANLIB.

# You may also specify config=Debug|Release
# or their corresponding lower case variants on make command line to select
# the corresponding default flags values.
ifeq ($(config),debug)
override config := Debug
endif
ifeq ($(config),release)
override config := Release
endif
ifeq ($(config),Debug)
CPPFLAGS ?= -DDEBUG
CFLAGS ?= -g -O0
CXXFLAGS ?= -g -O0
LDFLAGS ?= -g
else ifeq ($(config),Release)
CPPFLAGS ?= -DNDEBUG
CFLAGS ?= -O2
CXXFLAGS ?= -O2
else ifneq (,$(config))
$(warning Unknown configuration "$(config)")
endif

# Use "make RANLIB=''" for platforms without ranlib.
RANLIB ?= ranlib

CC := cc
CXX := c++

# The directory for the build files, may be overridden on make command line.
builddir = .

all: $(builddir)/ineffable

$(builddir)/ineffable: $(builddir)/ineffable_ineffable.o $(builddir)/ineffable_ineffable_lexer.o $(builddir)/ineffable_ineffable_parser.o $(builddir)/ineffable_da.o
	$(CXX) -o $@ $(LDFLAGS) $(builddir)/ineffable_ineffable.o $(builddir)/ineffable_ineffable_lexer.o $(builddir)/ineffable_ineffable_parser.o $(builddir)/ineffable_da.o -pthread

$(builddir)/ineffable_ineffable.o: ineffable.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -IDA ineffable.c

$(builddir)/ineffable_ineffable_lexer.o: ineffable_lexer.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -IDA ineffable_lexer.c

$(builddir)/ineffable_ineffable_parser.o: ineffable_parser.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -IDA ineffable_parser.c

$(builddir)/ineffable_da.o: DA/da.c
	$(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) -MD -MP -pthread -IDA DA/da.c

clean:
	rm -f *.o
	rm -f *.d
	rm -f $(builddir)/ineffable

.PHONY: all clean

# Dependencies tracking:
-include *.d
